### PR TITLE
Use solc 0.6.11

### PR DESCRIPTION
**Pull request by gbalabasquer**

### CODE REVIEW

**Comment by gbalabasquer** [comment]
All works with solc 0.6.11 but for some reason the latest version of dapptools takes x10 to compile in the CI.
Waiting for @icetan to confirm if some nix cache problem or actually something very different in dapptools that requires this much bigger time.

In the meanwhile all the rest can be checked.

**Comment by gbalabasquer** [comment]
CI problem is solved (at least a temporary solution) so we can move to review this PR.

**Review by brianmcmichael — APPROVED** [review]
LGTM

**Review by lucas-manuel — APPROVED** [review]
LGTM

**Review by godsflaw — APPROVED** [review]
LGTM

**Pull request merged**
